"""Add creators table and creator_relation_id to videos

Revision ID: 199819f50419
Revises: ab03c49701d3
Create Date: 2025-03-26 19:09:15.638706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199819f50419'
down_revision = 'ab03c49701d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_tutorials', sa.Column('creator_relation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'video_tutorials', 'creators', ['creator_relation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_tutorials', type_='foreignkey')
    op.drop_column('video_tutorials', 'creator_relation_id')
    # ### end Alembic commands ###
