"""Add video tutorial fields

Revision ID: 6b8e3ff87403
Revises: 
Create Date: 2025-03-26 15:26:45.539164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8e3ff87403'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_tutorials', sa.Column('key_points', sa.Text(), nullable=True))
    op.add_column('video_tutorials', sa.Column('kemono_id', sa.String(), nullable=True))
    op.add_column('video_tutorials', sa.Column('service', sa.String(), nullable=True))
    op.add_column('video_tutorials', sa.Column('creator_id', sa.String(), nullable=True))
    op.add_column('video_tutorials', sa.Column('added_date', sa.DateTime(), nullable=True))
    op.add_column('video_tutorials', sa.Column('published_date', sa.DateTime(), nullable=True))
    op.add_column('video_tutorials', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('video_tutorials', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_video_tutorials_kemono_id'), 'video_tutorials', ['kemono_id'], unique=False)
    op.create_foreign_key(None, 'video_tutorials', 'video_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_tutorials', type_='foreignkey')
    op.drop_index(op.f('ix_video_tutorials_kemono_id'), table_name='video_tutorials')
    op.drop_column('video_tutorials', 'category_id')
    op.drop_column('video_tutorials', 'tags')
    op.drop_column('video_tutorials', 'published_date')
    op.drop_column('video_tutorials', 'added_date')
    op.drop_column('video_tutorials', 'creator_id')
    op.drop_column('video_tutorials', 'service')
    op.drop_column('video_tutorials', 'kemono_id')
    op.drop_column('video_tutorials', 'key_points')
    # ### end Alembic commands ###
