"""add_category_to_champion_pool_entries

Revision ID: 824692065fd9
Revises: da3a0be767fb
Create Date: 2025-03-30 21:56:52.182370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824692065fd9'
down_revision = 'da3a0be767fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('champion_pool_entries', sa.Column('category', sa.String(), nullable=True))
    op.alter_column('champion_pools', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('champion_pools', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('champion_pool_entries', 'category')
    # ### end Alembic commands ###
